baseURL = "https://littledriver.net"
languageCode = "en-us"
title = "Littledriver's Blog"                    # site title  # 网站标题
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Littledriver's Blog"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 1

[params]
disqus = "xuran" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "/about"